Update node dependencies & node version
liip/django-template pull request #108
Opened 2021-10-12 13:05 UTC by ldgtd

- [x] Update node package dep. (major change from Webpack 4 to 5)
- [x] Update node image to v.16

2021-12-15 13:01 UTC, simonbru commented on {{cookiecutter.project_slug}}/Dockerfile-frontend
> -FROM node:10-buster
Don't forget to also update the node version in `Dockerfile` (i.e. use the repository `https://deb.nodesource.com/node_16.x`  instead of `.../node_10.x`

2021-12-15 14:08 UTC, LeBenLeBen requested changes

2021-12-15 14:08 UTC, LeBenLeBen commented on {{cookiecutter.project_slug}}/package-lock.json
> +  "lockfileVersion": 1,
This file is incomplete, it miss most dependencies. Also it seems to have been generated prior to the update to npm 7 as it’s using the previous lockfile version.

2021-12-15 14:08 UTC, LeBenLeBen commented on {{cookiecutter.project_slug}}/package.json
> +    "npm": "6"
Those two are wrong, it must be 16 and 8. Also I’m not sure we should specify them considering everything is already enforced in the Docker config.

2021-12-15 14:08 UTC, LeBenLeBen commented on {{cookiecutter.project_slug}}/webpack.config.js
> +  plugins.push(new webpack.HotModuleReplacementPlugin());
`webpack` is undefined here. Also this is not necessary, webpack-dev-server is `hot` by default and inject this automatically in dev.

2021-12-15 14:08 UTC, LeBenLeBen commented on {{cookiecutter.project_slug}}/webpack.config.js
> +      watch: true,
This is the default option already

2021-12-15 14:08 UTC, LeBenLeBen commented on {{cookiecutter.project_slug}}/package.json
> +    "start": "NODE_ENV=development webpack serve --hot",
`--hot` is the default now

2022-01-13 15:01 UTC, simonbru commented on {{cookiecutter.project_slug}}/Dockerfile-frontend
> -FROM node:10-buster
This has been done in https://github.com/liip/django-template/pull/110 (merged)

2022-03-28 09:04 UTC, LeBenLeBen approved these changes

2022-03-28 09:12 UTC, merged