SWING-150 removed django_cms, drifter and vagrant
liip/django-template pull request #126
Opened 2022-09-15 09:50 UTC by T4m

2022-09-20 18:23 UTC, felicemcc commented
Hello, I found as well:

**File: django-template/{{cookiecutter.project_slug}}/.gitignore**

- Still references to drifter and vagrant


**File: django-template/hooks/post_gen_project.py**

- Please remove install_drifter() function

- Look for these lines and remove them:
```
set_parameter(path, 'box_name', 'drifter/stretch64-base')
set_parameter(path, 'box_url', 'https://vagrantbox-public.liip.ch/drifter-stretch64-base.json')

```

**File: django-template/{{cookiecutter.project_slug}}/setup.cfg**

- References to drifter

2022-09-20 18:24 UTC, felicemcc commented on README.md
>  Go to http://my-project.lo/ and start hacking!
http://my-project.dockert.test/

2022-09-21 07:54 UTC, Nadeempoco commented on README.md
>  Go to http://my-project.lo/ and start hacking!
this is the link we should use?

2022-12-21 14:45 UTC, danickfort requested changes
@T4m @Nadeempoco Some small changes

2022-12-21 14:45 UTC, danickfort commented on README.md
> +Go to http://my-project.dockert.test/ and start hacking!
```suggestion
Go to http://my-project.docker.test/ and start hacking!
```

2022-12-21 14:45 UTC, danickfort commented on {{cookiecutter.project_slug}}/setup.cfg
>  default_section = THIRDPARTY
On line 6 of this file : Remove `{% if cookiecutter.virtualization_tool == 'drifter' %}virtualization/, {% endif %}`

2022-12-22 12:17 UTC, danickfort commented
looks good to me, I would merge the PR if I had permissions 😄  👍

2022-12-22 13:10 UTC, merged